name: Generate File List

on:
  push:
    branches:
      - main

runs:
  using: "composite"
  steps: 
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Generate file list
      shell: bash
      run: |
        # Specify the directory for which you want to generate the file list
        DIRECTORY_PATH="./test_data/"
        REPO_ROOT=$(realpath .)
        cd $DIRECTORY_PATH
        # List all files in the specified directory and output as JSON
        find ./*.mtf -type f > $REPO_ROOT/web/root/sample_file_names.txt
        mkdir $REPO_ROOT/web/root/sample_files/
        cp *.mtf $REPO_ROOT/web/root/sample_files/

    # - name: Commit
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: file-list
    #     path: file-list.json
